@startuml

[FrontendClient] <|-- [CustomersRoute]
[FrontendClient] <|-- [EmployeeRoute]

[CustomersRoute] <|-- [CustomersService]
[EmployeeRoute] <|-- [EmployeeService]

[NotificationsRoute] <|-- [NotificationService]
[NotificationsRoute] <|-- [EmployeeService]
@enduml
